"""Updated FTKOps model

Revision ID: 515428990617
Revises: 2c7afa085509
Create Date: 2024-11-06 04:09:19.285634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515428990617'
down_revision = '2c7afa085509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ftk_ops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_values', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('drive_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deleted_files', sa.Text(), nullable=True))
        batch_op.drop_column('operation')
        batch_op.drop_column('status')

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftk_imaged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('ftk_imaged')

    with op.batch_alter_table('ftk_ops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('operation', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('deleted_files')
        batch_op.drop_column('drive_info')
        batch_op.drop_column('hash_values')

    # ### end Alembic commands ###
